### ISSUE TITLE
Running on Chinook issue: No such file or directory: 'DATA/Par_file'

### ISSUE THREAD

**Issue by ytian159** [adjtomo/seisflows#169] opened 2023-04-03 21:14 UTC
I was trying to submit some forward simulation jobs on Chinoo04 via seisflows. I have specified my own DATA DADABASE and bin directory. But I have this error message:
>2023-04-03 03:02:07 | INFO  | forward.py -> run_forward_simulations():L394
 evaluating objective function for source 20160518032548320
2023-04-03 03:02:07 | DEBUG | forward.py -> run_forward_simulations():L396
> running forward simulation with 'Specfem3D'
Traceback (most recent call last):
  File "/var/spool/slurm/job02423/slurm_script", line 110, in <module>
    func(**kwargs)
  File "/import/c1/ERTHQUAK/ytian4/simutils/seisflows/seisflows/workflow/forward.py", line 409, in run_forward_simulations
    self.solver.forward_simulation(
  File "/import/c1/ERTHQUAK/ytian4/simutils/seisflows/seisflows/solver/specfem3d.py", line 148, in forward_simulation
    setpar(key="ATTENUATION", val=".false`.", file="DATA/Par_file")
  File "/import/c1/ERTHQUAK/ytian4/simutils/seisflows/seisflows/tools/specfem.py", line 137, in setpar
    key_out, val_out, i = getpar(key, file, delim, match_partial)
  File "/import/c1/ERTHQUAK/ytian4/simutils/seisflows/seisflows/tools/specfem.py", line 79, in getpar
    lines = open(file, "r").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'DATA/Par_file'
>
I only changed those three paths. It could run before my changes. What was the problem? I'm running it at : '/import/c1/ERTHQUAK/ytian4/seisflows_workdir'. The parameter file is located here.

Thanks,
Yuan

**Comment by bch0w** [comment] 2023-04-04 17:10
Hi @ytian159, looks like for some reason you have 4 solver directories but you have only specified `ntask`==2 in your parameter file. The two chosen events did not seem to initialize properly, and they are missing all files in their respective DATA/ directories:

That is, comparing: `/import/c1/ERTHQUAK/ytian4/seisflows_workdir/scratch/solver/mainsolver/DATA/`
to: `/import/c1/ERTHQUAK/ytian4/seisflows_workdir/scratch/solver/20160518032548320/DATA/`

SeisFlows only takes the first `ntask` events in `path_specfem_data`, in alphabetical order, which looks like it would be `20160114190410727` and `20160518032548320`, but for some reason `20190411104245609` is linked as your mainsolver, which makes it seem like perhaps this was use for a previous run and now there are new events being added but not properly intialized.

I think the first thing to try is a `seisflows restart` to clear out the existing working directory and re-run the workflow (this will delete everything in the working directory so if you need these files, copy them somewhere safe before running this command). The expected behavior is that SeisFlows will run forward simulations for `20160114190410727` and `20160518032548320`. 

If you encounter the same issue then please let me know, there may be something else happening.

**Comment by ytian159** [comment] 2023-04-06 06:06
Hi Bryant,
I still have the same problem after restarting seisflows. I changed the number of tasks and restarted several times. The error messages are the same. 
Yuan

**Comment by bch0w** [comment] 2023-04-06 17:13
Hi @ytian159, got it! There was an interesting thing going on where the initialization of the solver directory was ignoring all files which contained a string matching the source prefix (in your case, 'CMTSOLUTION'). Since your full directory contains the string 'CMTSOLUTION', all the files were getting ignored, and thus the empty DATA/ directory, and the missing DATA/Par_file.

I just pushed a fix in the latest `devel` branch ([cb1065a](https://github.com/adjtomo/seisflows/commit/cb1065acebc3d9875fa1e2c859fcef16307bde76)) that should deal with this by only looking at the filenames (not full path), and only excluding files that start with the source prefix (not contain it). Hopefully that works for you and that you don't run into this issue again.

**Comment by ytian159** [comment] 2023-04-06 20:25
Thank you so much. It has finished running without issue.
Yuan

**Comment by bch0w** [comment] 2023-07-12 22:33
Closing as complete! Please re-open if this issue persists for you.

**Closed by bch0w** 2023-07-12 22:33 UTC
